version: '3.8'
services:
    db:
      image: mongo:4.4.3
      restart: always
      environment:
        # mongodb client connection
        MONGO_INITDB_ROOT_USERNAME: 
        MONGO_INITDB_ROOT_PASSWORD: 
      ports:
        - "27018:27017"
    app:
      build:
        context: .
      command: bundle exec rails s -p 3000 -b '0.0.0.0'
      volumes:
        - ".:/rh-training-plan-api"
      ports: 
        - "3001:3000"
      depends_on:
        - db
      links:
        - db